<?php
/**
 * FormattedTime
 *
 * PHP version 5
 *
 * @category Class
 * @package  Xvilo\Track\ApiServer\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * TRACK API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Xvilo\Track\ApiServer\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the FormattedTime model.
 *
 * @package Xvilo\Track\ApiServer\Model
 * @author  OpenAPI Generator team
 */
class FormattedTime 
{
        /**
     * @var string|null
     * @SerializedName("hours")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $hours;

    /**
     * @var string|null
     * @SerializedName("minutes")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $minutes;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->hours = isset($data['hours']) ? $data['hours'] : null;
        $this->minutes = isset($data['minutes']) ? $data['minutes'] : null;
    }

    /**
     * Gets hours.
     *
     * @return string|null
     */
    public function getHours(): ?string
    {
        return $this->hours;
    }

    /**
     * Sets hours.
     *
     * @param string|null $hours
     *
     * @return $this
     */
    public function setHours(string $hours = null)
    {
        $this->hours = $hours;

        return $this;
    }

    /**
     * Gets minutes.
     *
     * @return string|null
     */
    public function getMinutes(): ?string
    {
        return $this->minutes;
    }

    /**
     * Sets minutes.
     *
     * @param string|null $minutes
     *
     * @return $this
     */
    public function setMinutes(string $minutes = null)
    {
        $this->minutes = $minutes;

        return $this;
    }
}


