<?php
/**
 * WeekTotals
 *
 * PHP version 5
 *
 * @category Class
 * @package  Xvilo\Track\ApiServer\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * TRACK API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Xvilo\Track\ApiServer\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the WeekTotals model.
 *
 * @package Xvilo\Track\ApiServer\Model
 * @author  OpenAPI Generator team
 */
class WeekTotals 
{
        /**
     * @var Xvilo\Track\ApiServer\Model\FormattedTime
     * @SerializedName("totalHours")
     * @Assert\NotNull()
     * @Assert\Type("Xvilo\Track\ApiServer\Model\FormattedTime")
     * @Type("Xvilo\Track\ApiServer\Model\FormattedTime")
     */
    protected $totalHours;

    /**
     * @var Xvilo\Track\ApiServer\Model\WeekTotalsWeekDayTotals[]
     * @SerializedName("weekDayTotals")
     * @Assert\NotNull()
     * @Assert\All({
     *   @Assert\Type("Xvilo\Track\ApiServer\Model\WeekTotalsWeekDayTotals")
     * })
     * @Type("array<Xvilo\Track\ApiServer\Model\WeekTotalsWeekDayTotals>")
     */
    protected $weekDayTotals;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->totalHours = isset($data['totalHours']) ? $data['totalHours'] : null;
        $this->weekDayTotals = isset($data['weekDayTotals']) ? $data['weekDayTotals'] : null;
    }

    /**
     * Gets totalHours.
     *
     * @return Xvilo\Track\ApiServer\Model\FormattedTime
     */
    public function getTotalHours(): FormattedTime
    {
        return $this->totalHours;
    }

    /**
     * Sets totalHours.
     *
     * @param Xvilo\Track\ApiServer\Model\FormattedTime $totalHours
     *
     * @return $this
     */
    public function setTotalHours(FormattedTime $totalHours)
    {
        $this->totalHours = $totalHours;

        return $this;
    }

    /**
     * Gets weekDayTotals.
     *
     * @return Xvilo\Track\ApiServer\Model\WeekTotalsWeekDayTotals[]
     */
    public function getWeekDayTotals(): array
    {
        return $this->weekDayTotals;
    }

    /**
     * Sets weekDayTotals.
     *
     * @param Xvilo\Track\ApiServer\Model\WeekTotalsWeekDayTotals[] $weekDayTotals
     *
     * @return $this
     */
    public function setWeekDayTotals(array $weekDayTotals)
    {
        $this->weekDayTotals = $weekDayTotals;

        return $this;
    }
}


