<?php
/**
 * WeekTotalsWeekDayTotals
 *
 * PHP version 5
 *
 * @category Class
 * @package  Xvilo\Track\ApiServer\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * TRACK API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Xvilo\Track\ApiServer\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the WeekTotalsWeekDayTotals model.
 *
 * @package Xvilo\Track\ApiServer\Model
 * @author  OpenAPI Generator team
 */
class WeekTotalsWeekDayTotals 
{
        /**
     * Date the timer is for
     *
     * @var \DateTime|null
     * @SerializedName("date")
     * @Assert\Date()
     * @Type("DateTime")
     */
    protected $date;

    /**
     * @var Xvilo\Track\ApiServer\Model\FormattedTime|null
     * @SerializedName("totalHours")
     * @Assert\Type("Xvilo\Track\ApiServer\Model\FormattedTime")
     * @Type("Xvilo\Track\ApiServer\Model\FormattedTime")
     */
    protected $totalHours;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->date = isset($data['date']) ? $data['date'] : null;
        $this->totalHours = isset($data['totalHours']) ? $data['totalHours'] : null;
    }

    /**
     * Gets date.
     *
     * @return \DateTime|null
     */
    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    /**
     * Sets date.
     *
     * @param \DateTime|null $date  Date the timer is for
     *
     * @return $this
     */
    public function setDate(\DateTime $date = null)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Gets totalHours.
     *
     * @return Xvilo\Track\ApiServer\Model\FormattedTime|null
     */
    public function getTotalHours(): ?FormattedTime
    {
        return $this->totalHours;
    }

    /**
     * Sets totalHours.
     *
     * @param Xvilo\Track\ApiServer\Model\FormattedTime|null $totalHours
     *
     * @return $this
     */
    public function setTotalHours(FormattedTime $totalHours = null)
    {
        $this->totalHours = $totalHours;

        return $this;
    }
}


