<?php
/**
 * TimerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Xvilo\Track\ApiServer\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * TRACK API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Xvilo\Track\ApiServer\Model;

/**
 * TimerTest Class Doc Comment
 *
 * @category    Class */
// * @description Timer
/**
 * @package     Xvilo\Track\ApiServer\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class TimerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Timer"
     */
    public function testTimer()
    {
        $testTimer = new Timer();
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "isRunning"
     */
    public function testPropertyIsRunning()
    {
    }

    /**
     * Test attribute "timeRecorded"
     */
    public function testPropertyTimeRecorded()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "gitlab"
     */
    public function testPropertyGitlab()
    {
    }

    /**
     * Test attribute "formatted"
     */
    public function testPropertyFormatted()
    {
    }
}
