<?php
/**
 * WeekTotalsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Xvilo\Track\ApiServer\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * TRACK API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Xvilo\Track\ApiServer\Model;

/**
 * WeekTotalsTest Class Doc Comment
 *
 * @category    Class */
// * @description WeekTotals
/**
 * @package     Xvilo\Track\ApiServer\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class WeekTotalsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WeekTotals"
     */
    public function testWeekTotals()
    {
        $testWeekTotals = new WeekTotals();
    }

    /**
     * Test attribute "totalHours"
     */
    public function testPropertyTotalHours()
    {
    }

    /**
     * Test attribute "weekDayTotals"
     */
    public function testPropertyWeekDayTotals()
    {
    }
}
