<?php
/**
 * AdministrationApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Xvilo\Track\ApiServer
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * TRACK API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Xvilo\Track\ApiServer\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Xvilo\Track\ApiServer\Model\Error;
use Xvilo\Track\ApiServer\Model\WeekTotals;

/**
 * AdministrationApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Xvilo\Track\ApiServer\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface AdministrationApiInterface
{

    /**
     * Operation listTotalsForYearAndWeek
     *
     * List all timers
     *
     * @param  string $year  The year for the totals to return (required)
     * @param  string $week  The week for the totals to return (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Xvilo\Track\ApiServer\Model\WeekTotals
     *
     */
    public function listTotalsForYearAndWeek(string $year, string $week, &$responseCode, array &$responseHeaders);
}
