<?php
/**
 * TimersApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Xvilo\Track\ApiServer
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * TRACK API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Xvilo\Track\ApiServer\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Xvilo\Track\ApiServer\Model\Date;
use Xvilo\Track\ApiServer\Model\Error;
use Xvilo\Track\ApiServer\Model\Timer;

/**
 * TimersApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Xvilo\Track\ApiServer\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface TimersApiInterface
{

    /**
     * Operation listTimers
     *
     * List all timers
     *
     * @param  \DateTime $date  The Date for the timers to return (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Xvilo\Track\ApiServer\Model\Timer[]
     *
     */
    public function listTimers(\DateTime $date, &$responseCode, array &$responseHeaders);
}
